// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxESC1OXDnKiFvsRbpKmtHyw-J_eEjyyw',
    appId: '1:185504596076:web:394a053e229687ecfc5849',
    messagingSenderId: '185504596076',
    projectId: 'playthefit-b8637',
    authDomain: 'playthefit-b8637.firebaseapp.com',
    storageBucket: 'playthefit-b8637.firebasestorage.app',
    measurementId: 'G-8HF9PK7RJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_AeuN9C6gCq5hJTux28JRgp1oR_oGHPU',
    appId: '1:185504596076:android:8fb73ee49d59c228fc5849',
    messagingSenderId: '185504596076',
    projectId: 'playthefit-b8637',
    storageBucket: 'playthefit-b8637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaf7OJ_yS_JvioevfJhE7mwANH3m5cnj8',
    appId: '1:185504596076:ios:1b7c6237ed85845bfc5849',
    messagingSenderId: '185504596076',
    projectId: 'playthefit-b8637',
    storageBucket: 'playthefit-b8637.firebasestorage.app',
    iosBundleId: 'com.example.playthefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaf7OJ_yS_JvioevfJhE7mwANH3m5cnj8',
    appId: '1:185504596076:ios:1b7c6237ed85845bfc5849',
    messagingSenderId: '185504596076',
    projectId: 'playthefit-b8637',
    storageBucket: 'playthefit-b8637.firebasestorage.app',
    iosBundleId: 'com.example.playthefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxESC1OXDnKiFvsRbpKmtHyw-J_eEjyyw',
    appId: '1:185504596076:web:92adb3b64c453ccafc5849',
    messagingSenderId: '185504596076',
    projectId: 'playthefit-b8637',
    authDomain: 'playthefit-b8637.firebaseapp.com',
    storageBucket: 'playthefit-b8637.firebasestorage.app',
    measurementId: 'G-SVYVG7ZT9G',
  );
}
